import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'lat_lng.dart';
import 'place.dart';
import '../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/firebase_auth/auth_util.dart';

String patientidautogenerated() {
  // 1 to 100 numbers
  final x = math.Random();
  int random1to100 = x.nextInt(100);

  String customString = 'DASH';
  String patientid = customString;
  int len = patientid.length;
  patientid = patientid.padRight(7, '0');
  patientid = patientid.replaceRange(len - 1, len, random1to100.toString());
  return patientid;
}
